# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/data1/xiongyuming/downloads/cmake-3.31.5-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(CMAKE_COMMAND) -E cmake_progress_start /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator/CMakeFiles /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator/gpgpu-sim//CMakeFiles/progress.marks
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpgpu-sim/all
	$(CMAKE_COMMAND) -E cmake_progress_start /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpgpu-sim/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpgpu-sim/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpgpu-sim/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
gpgpu-sim/CMakeFiles/gen_build_string.dir/rule:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpgpu-sim/CMakeFiles/gen_build_string.dir/rule
.PHONY : gpgpu-sim/CMakeFiles/gen_build_string.dir/rule

# Convenience name for target.
gen_build_string: gpgpu-sim/CMakeFiles/gen_build_string.dir/rule
.PHONY : gen_build_string

# fast build rule for target.
gen_build_string/fast:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f gpgpu-sim/CMakeFiles/gen_build_string.dir/build.make gpgpu-sim/CMakeFiles/gen_build_string.dir/build
.PHONY : gen_build_string/fast

# Convenience name for target.
gpgpu-sim/CMakeFiles/cudart.dir/rule:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpgpu-sim/CMakeFiles/cudart.dir/rule
.PHONY : gpgpu-sim/CMakeFiles/cudart.dir/rule

# Convenience name for target.
cudart: gpgpu-sim/CMakeFiles/cudart.dir/rule
.PHONY : cudart

# fast build rule for target.
cudart/fast:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f gpgpu-sim/CMakeFiles/cudart.dir/build.make gpgpu-sim/CMakeFiles/cudart.dir/build
.PHONY : cudart/fast

# Convenience name for target.
gpgpu-sim/CMakeFiles/entrypoint.dir/rule:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpgpu-sim/CMakeFiles/entrypoint.dir/rule
.PHONY : gpgpu-sim/CMakeFiles/entrypoint.dir/rule

# Convenience name for target.
entrypoint: gpgpu-sim/CMakeFiles/entrypoint.dir/rule
.PHONY : entrypoint

# fast build rule for target.
entrypoint/fast:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(MAKE) $(MAKESILENT) -f gpgpu-sim/CMakeFiles/entrypoint.dir/build.make gpgpu-sim/CMakeFiles/entrypoint.dir/build
.PHONY : entrypoint/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gen_build_string"
	@echo "... cudart"
	@echo "... entrypoint"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /data1/xiongyuming/gpu/accel-sim-framework/gpu-simulator && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

